create table if not exists public.blocked_users (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint blocked_users_not_self check (blocker_id <> blocked_id)
);

create table if not exists public.user_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users(id) on delete set null,
  reported_user_id uuid references auth.users(id) on delete set null,
  reported_display_name text,
  category text not null check (
    category in ('inappropriate-name', 'harassment', 'spam', 'other')
  ),
  details text check (char_length(details) <= 1000),
  context text not null check (context in ('leaderboard', 'friends')),
  status text not null default 'pending' check (
    status in ('pending', 'reviewed', 'resolved', 'dismissed')
  ),
  created_at timestamptz not null default now()
);

create index if not exists blocked_users_blocked_id_idx
  on public.blocked_users (blocked_id);

create index if not exists user_reports_status_created_at_idx
  on public.user_reports (status, created_at desc);

alter table public.blocked_users enable row level security;
alter table public.user_reports enable row level security;

revoke all on public.blocked_users from anon, authenticated;
revoke all on public.user_reports from anon, authenticated;

create or replace function public.block_user(p_target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_target_user_id is null or p_target_user_id = current_user_id then
    raise exception 'Invalid user';
  end if;

  insert into public.blocked_users (blocker_id, blocked_id)
  values (current_user_id, p_target_user_id)
  on conflict do nothing;

  delete from public.friendships
  where (requester_id = current_user_id and addressee_id = p_target_user_id)
     or (requester_id = p_target_user_id and addressee_id = current_user_id);
end;
$$;

create or replace function public.unblock_user(p_target_user_id uuid)
returns void
language sql
security definer
set search_path = public, auth
as $$
  delete from public.blocked_users
  where blocker_id = auth.uid() and blocked_id = p_target_user_id;
$$;

create or replace function public.get_hidden_user_ids()
returns table (user_id uuid)
language sql
stable
security definer
set search_path = public, auth
as $$
  select blocked_id from public.blocked_users where blocker_id = auth.uid()
  union
  select blocker_id from public.blocked_users where blocked_id = auth.uid();
$$;

create or replace function public.get_my_blocked_users()
returns table (user_id uuid, display_name text)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    blocks.blocked_id,
    coalesce(settings.display_name, 'Blocked user')
  from public.blocked_users as blocks
  left join public.user_settings as settings
    on settings.user_id = blocks.blocked_id
  where blocks.blocker_id = auth.uid()
  order by blocks.created_at desc;
$$;

create or replace function public.report_user(
  p_target_user_id uuid,
  p_category text,
  p_details text default null,
  p_context text default 'leaderboard'
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
  target_display_name text;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_target_user_id is null or p_target_user_id = current_user_id then
    raise exception 'Invalid user';
  end if;
  if p_category not in ('inappropriate-name', 'harassment', 'spam', 'other') then
    raise exception 'Invalid report category';
  end if;
  if p_context not in ('leaderboard', 'friends') then
    raise exception 'Invalid report context';
  end if;
  if char_length(coalesce(p_details, '')) > 1000 then
    raise exception 'Report details are too long';
  end if;

  select display_name into target_display_name
  from public.user_settings
  where user_id = p_target_user_id;

  insert into public.user_reports (
    reporter_id,
    reported_user_id,
    reported_display_name,
    category,
    details,
    context
  ) values (
    current_user_id,
    p_target_user_id,
    target_display_name,
    p_category,
    nullif(trim(p_details), ''),
    p_context
  );
end;
$$;

create or replace function public.prevent_blocked_friendship()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if exists (
    select 1
    from public.blocked_users
    where (blocker_id = new.requester_id and blocked_id = new.addressee_id)
       or (blocker_id = new.addressee_id and blocked_id = new.requester_id)
  ) then
    raise exception 'Friend request unavailable';
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_blocked_friendship on public.friendships;
create trigger prevent_blocked_friendship
before insert or update on public.friendships
for each row execute function public.prevent_blocked_friendship();

revoke all on function public.block_user(uuid) from public;
revoke all on function public.unblock_user(uuid) from public;
revoke all on function public.get_hidden_user_ids() from public;
revoke all on function public.get_my_blocked_users() from public;
revoke all on function public.report_user(uuid, text, text, text) from public;

grant execute on function public.block_user(uuid) to authenticated;
grant execute on function public.unblock_user(uuid) to authenticated;
grant execute on function public.get_hidden_user_ids() to authenticated;
grant execute on function public.get_my_blocked_users() to authenticated;
grant execute on function public.report_user(uuid, text, text, text) to authenticated;
